### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by ASSlili** [makoto56/penetration-suite-toolkit#79]
直接导入提示SHA digest of file windows10-disk1.vmdk does not match manifest，删除mf文件后导入进系统提示0XC0000225

**Comment by makoto56** [comment]
> 直接导入提示SHA digest of file windows10-disk1.vmdk does not match manifest，删除mf文件后导入进系统提示0XC0000225

可以将.ova文件重命名为.zip文件，直接用7-zip等压缩软件解压即可。

**Comment by makoto56** [comment]
> 直接导入提示SHA digest of file windows10-disk1.vmdk does not match manifest，删除mf文件后导入进系统提示0XC0000225

**Comment by makoto56** [comment]
> 直接导入提示SHA digest of file windows10-disk1.vmdk does not match manifest，删除mf文件后导入进系统提示0XC0000225

我会重新上传一个压缩版本的
