### ISSUE TITLE
我开启了clashForWin还是不能上谷歌

### ISSUE THREAD

**Issue by Batman0506** [makoto56/penetration-suite-toolkit#80]
我开启了clashForWin还是不能上谷歌
刚安装好的虚拟机，网络是nat的，有哪个大佬试过吗

**Comment by makoto56** [comment]
> 我开启了clashForWin还是不能上谷歌 刚安装好的虚拟机，网络是nat的，有哪个大佬试过吗
请检查windows本地代理设置，我测试了v2ray、ssr和openvpn，均可正常科学上网。

**Comment by Batman0506** [comment]
有大佬能解决的吗
