### ISSUE TITLE
J8大的师傅们 你们5.0版本有密码吗？？？？

### ISSUE THREAD

**Issue by WasteMaterial** [makoto56/penetration-suite-toolkit#88]
我这是真没看到

![image](https://github.com/makoto56/penetration-suite-toolkit/assets/32891131/84d430a5-3bc9-49a5-b3e2-2b807c524ad8)

**Comment by WasteMaterial** [comment]
数据库密码
扫描工具密码
工具激活密钥
实在不行把密码写到系统桌面创个文件吧

**Comment by iuu6** [comment]
请认真阅读本项目**README文件**！

MariaDB: Mysql 数据库
username: root
password: sqladmin

Neo4j
username: root
password: sqladmin

Oracle 19c
username: system
password: sqladmin

sqlServer 2019: sqlServer 2019 专业版
username: sa
password: sqladmin

Acunetix: 24.2.240226074(注册版)
username: admin@awvs.com
password: Admin@awvs.com

Nessus: 10.7.1(注册版)
username: admin
password: password

Kali:WSL Kali Linux 2024.1
username: kali password: kali
username: root password: root


等等……
